-- Generated from server/src/lobbyOptionContract.json
-- Do not edit this file by hand; run `node scripts/lobbyOptionContractSync.mjs <output-path>` from the server project.
MP.LOBBY_OPTION_BOOLEAN_KEYS = {
	gold_on_life_loss = true,
	no_gold_on_round_loss = true,
	death_on_round_loss = true,
	disable_live_and_timer_hud = true,
	different_decks = true,
	different_seeds = true,
	forced_config = true,
	legacy_smallworld = true,
	multiplayer_jokers = true,
	normal_bosses = true,
	preview_disabled = true,
	random_loadout = true,
	team_card_sync = true,
	team_hand_level_sync = true,
	team_money_sync = true,
	the_order = true,
	timer = true,
}

MP.LOBBY_OPTION_NUMERIC_KEYS = {
	bonus_consumable_slots = true,
	bonus_discards = true,
	bonus_hands = true,
	bonus_joker_slots = true,
	bonus_money = true,
	coop_blind_scaling_per_player = true,
	max_players = true,
	pvp_custom_winners = true,
	pvp_custom_winners_percent = true,
	pvp_start_round = true,
	showdown_starting_antes = true,
	stake = true,
	starting_lives = true,
	timer_base_seconds = true,
	timer_forgiveness = true,
	timer_increment_seconds = true,
}

MP.LOBBY_OPTION_STRING_KEYS = {
	back = true,
	challenge = true,
	cocktail = true,
	custom_bans = true,
	custom_seed = true,
	modifier_layers = true,
	pvp_score_rule = true,
	ruleset = true,
	sleeve = true,
	weekly = true,
}

MP.SHARED_LOBBY_DECK_OPTION_KEYS = {
	back = true,
	sleeve = true,
	stake = true,
	challenge = true,
	cocktail = true,
}

local BASE_DEFAULT_LOBBY_OPTION_VALUES = {
	back = "Red Deck",
	bonus_consumable_slots = 0,
	bonus_discards = 0,
	bonus_hands = 0,
	bonus_joker_slots = 0,
	bonus_money = 0,
	challenge = "",
	cocktail = "",
	custom_bans = "",
	custom_seed = "random",
	coop_blind_scaling_per_player = 1,
	death_on_round_loss = true,
	different_decks = false,
	different_seeds = false,
	disable_live_and_timer_hud = false,
	forced_config = false,
	gold_on_life_loss = true,
	legacy_smallworld = false,
	modifier_layers = "",
	multiplayer_jokers = true,
	no_gold_on_round_loss = false,
	normal_bosses = false,
	preview_disabled = false,
	random_loadout = false,
	pvp_custom_winners = 1,
	pvp_custom_winners_percent = 50,
	pvp_score_rule = "highest",
	team_card_sync = false,
	team_hand_level_sync = true,
	team_money_sync = true,
	pvp_start_round = 2,
	ruleset = "ruleset_mp_standard_ranked",
	showdown_starting_antes = 3,
	sleeve = "sleeve_casl_none",
	stake = 1,
	starting_lives = 4,
	the_order = true,
	timer = true,
	timer_base_seconds = 150,
	timer_forgiveness = 0,
	timer_increment_seconds = 60,
}

local GROUP_LOBBY_OPTION_DEFAULT_VALUES = {
	max_players = 16,
	pvp_custom_winners = 8,
	pvp_custom_winners_percent = 50,
}

local function get_lobby_type_default_option_overrides(lobby_type)
	return {
		team_card_sync = lobby_type == MP.LOBBY_TYPES.TEAMS or lobby_type == MP.LOBBY_TYPES.COOP,
	}
end

function MP.build_lobby_option_defaults(lobby_type)
	local defaults = {}
	for key, value in pairs(BASE_DEFAULT_LOBBY_OPTION_VALUES) do
		defaults[key] = value
	end

	local effective_lobby_type = lobby_type or (MP.LOBBY and MP.LOBBY.lobby_type) or nil
	if MP.is_group_lobby_type and MP.is_group_lobby_type(effective_lobby_type) then
		for key, value in pairs(GROUP_LOBBY_OPTION_DEFAULT_VALUES) do
			defaults[key] = value
		end
	end

	for key, value in pairs(get_lobby_type_default_option_overrides(effective_lobby_type)) do
		defaults[key] = value
	end

	return defaults
end
