-- Generated from server/src/lobbyOptionContract.json
-- Do not edit this file by hand; run `node scripts/lobbyOptionContractSync.mjs` from the server project.
MP.LOBBY_OPTION_BOOLEAN_KEYS = {
	gold_on_life_loss = true,
	no_gold_on_round_loss = true,
	death_on_round_loss = true,
	disable_live_and_timer_hud = true,
	different_decks = true,
	different_seeds = true,
	forced_config = true,
	ffa_scoring_beat_average = true,
	legacy_smallworld = true,
	multiplayer_jokers = true,
	normal_bosses = true,
	preview_disabled = true,
	the_order = true,
	timer = true,
}

MP.LOBBY_OPTION_NUMERIC_KEYS = {
	coop_blind_scaling_per_player = true,
	max_players = true,
	pvp_countdown_seconds = true,
	pvp_start_round = true,
	showdown_starting_antes = true,
	stake = true,
	starting_lives = true,
	timer_base_seconds = true,
	timer_forgiveness = true,
	timer_increment_seconds = true,
}

MP.LOBBY_OPTION_STRING_KEYS = {
	back = true,
	challenge = true,
	cocktail = true,
	custom_seed = true,
	ruleset = true,
	sleeve = true,
	weekly = true,
}

MP.SHARED_LOBBY_DECK_OPTION_KEYS = {
	back = true,
	sleeve = true,
	stake = true,
	challenge = true,
	cocktail = true,
}

local BASE_DEFAULT_LOBBY_OPTION_VALUES = {
	back = "Red Deck",
	challenge = "",
	cocktail = "",
	custom_seed = "random",
	coop_blind_scaling_per_player = 1,
	death_on_round_loss = true,
	different_decks = false,
	different_seeds = false,
	disable_live_and_timer_hud = false,
	ffa_scoring_beat_average = false,
	forced_config = false,
	gold_on_life_loss = true,
	legacy_smallworld = false,
	multiplayer_jokers = true,
	no_gold_on_round_loss = false,
	normal_bosses = false,
	preview_disabled = false,
	pvp_countdown_seconds = 3,
	pvp_start_round = 2,
	ruleset = "ruleset_mp_standard_ranked",
	showdown_starting_antes = 3,
	sleeve = "sleeve_casl_none",
	stake = 1,
	starting_lives = 4,
	the_order = true,
	timer = true,
	timer_base_seconds = 150,
	timer_forgiveness = 0,
	timer_increment_seconds = 60,
}

local GROUP_LOBBY_OPTION_DEFAULT_VALUES = {
	max_players = 16,
}

function MP.build_lobby_option_defaults(lobby_type)
	local defaults = {}
	for key, value in pairs(BASE_DEFAULT_LOBBY_OPTION_VALUES) do
		defaults[key] = value
	end

	local effective_lobby_type = lobby_type or (MP.LOBBY and MP.LOBBY.lobby_type) or nil
	if MP.is_group_lobby_type and MP.is_group_lobby_type(effective_lobby_type) then
		for key, value in pairs(GROUP_LOBBY_OPTION_DEFAULT_VALUES) do
			defaults[key] = value
		end
	end

	return defaults
end
